### ISSUE TITLE
The depot »https://download.docker.com/linux/ubuntu bullseye Release«has no release file

### ISSUE THREAD

**Issue by luisbruegelhka** [Ar-Ray-code/rpi-bullseye-ros2#8] opened 2022-10-12 13:50 UTC
I'm following the instructions on installing this RaspiOS with ROS2 when the following mistake occurred, while doing the Command "sudo apt update":

The depot »https://download.docker.com/linux/ubuntu bullseye Release«has no release file

I'm wondering why, because i am installing on a Raspberry 4 with RaspiOS Bullyseye arm64.

Can someone hepl me to fix this issue so i can go on with the installations?

**Comment by Ar-Ray-code** [comment] 2022-10-12 14:06
I can't guess what the keywords `sudo apt update`, `docker` and `RaspiOS` mean, so please give me some more details.
At the very least, I need your purpose and the reference URL of the cause of the error.

**Comment by mmurasawa** [comment] 2022-10-12 14:28
bullseye is debian.

https://download.docker.com/linux/debian/dists/bullseye/

**Comment by luisbruegelhka** [comment] 2022-10-13 12:34
Keyword explanation:
"Sudo apt update": Command which is used to download package information from all configured sources
"docker": kind of an Virtual machine
"RaspiOS": Operating System used on the Raspberry Pi 4, in my case it's Raspios bullseye arm64

My Purpose is to install ROS2 on the mentioned RaspberryPi. So i dont understand why a missing ubuntu file is a problem.
Hope this helped you...

**Comment by Ar-Ray-code** [comment] 2022-10-13 13:25
Here is debian (arm64) docker installation tutorial. 

https://docs.docker.com/engine/install/debian/

I checked it on an AWS server, but it probably works on Raspbian as well.


```bash
uname -a
> Linux ip-172-31-18-171 5.10.0-14-cloud-arm64 #1 SMP Debian 5.10.113-1 (2022-04-29) aarch64 GNU/Linux
```

**Comment by luisbruegelhka** [comment] 2022-10-13 13:29
Thank you, will try that tomorrow

**Comment by Ar-Ray-code** [comment] 2023-09-06 09:29
How is the progress?
This question is not directly related to the content of the repository, so I will close it for now.
If you have any further questions, please open an issue 👋

**Closed by Ar-Ray-code** 2023-09-06 09:29 UTC
